version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=symmy_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: ['.:/app']
    ports: ["8000:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_KEY=change-me-in-production
      - ALLOWED_HOSTS=localhost,0.0.0.0
      - SECURE_SSL_REDIRECT=false
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - RUN_MIGRATIONS=true
    depends_on: [db, redis]
  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes: ['.:/app']
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_KEY=change-me-in-production
      - ALLOWED_HOSTS=localhost
      - SECURE_SSL_REDIRECT=false
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on: [web]
  beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes: ['.:/app']
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_KEY=change-me-in-production
      - ALLOWED_HOSTS=localhost
      - SECURE_SSL_REDIRECT=false
      - POSTGRES_HOST=db
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on: [web]
volumes:
  postgres_data:
